Delete content of state folder instead of the folder itself
dfuse-io/manageos pull request #8
Opened 2020-06-16 11:16 UTC by fschoell

It's common to have state and block folder mounted (for example when using ZFS). Using RemoveAll on the state folder will fail in that case as mounted ZFS filesystems cannot be deleted. This change removes the content of the state dir instead of the folder itself.

2020-06-16 12:02 UTC, fschoell commented
Same goes for `hasData()` that won't work if the folders are mounted and already exist (but do not have any content).

2020-06-16 13:02 UTC, maoueh requested changes
Small stuff. We recently did a major refactoring of `manageos` to extract the specific `nodeos` portion and move it back in `dfuse-eosio` directly. I'm going to check with the team for the best way to handle the merge of this PR.

2020-06-16 13:02 UTC, maoueh commented on superviser/nodeos/superviser.go
> +	if err != nil || len(dir) < 3 {
I would be more forgiving here and use the same logic as for the `state` dir, if there is something in there, we have `data`.

2020-06-16 13:02 UTC, maoueh commented on superviser/nodeos/superviser.go
> +			return fmt.Errorf("cannot delete state: %w", err)
```suggestion
			return fmt.Errorf("cannot delete state element: %w", err)
```

2020-06-16 13:14 UTC, fschoell commented on superviser/nodeos/superviser.go
> +	if err != nil || len(dir) < 3 {
Yeah makes sense

2020-07-09 21:40 UTC, maoueh commented
Closing as this has been moved to github.com/dfuse-io/dfuse-eosio repository, sent you instructions on Telegram about how to port the PR to there.

2020-07-09 21:40 UTC, closed without merging